export const routes = {
  root: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminOrgs: "/admin/organizations",
  selectOrganization: "/select-organization",
  organization: "/organization",
  acceptInvitation: "/accept-invitation",
  profile: "/profile",
  settings: "/settings",
  budgets: "/budgets",
  budgetDetail: (id: string) => `/budgets/${id}`,
  transactions: "/transactions",
} as const;
